/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActeurChoix: typeof import('./src/components/ActeurChoix.vue')['default']
    ActeurData: typeof import('./src/components/ActeurData.vue')['default']
    AnnonceTravauxData: typeof import('./src/components/AnnonceTravauxData.vue')['default']
    AnnonceTravauxImport: typeof import('./src/components/AnnonceTravauxImport.vue')['default']
    AnnonceTravauxListe: typeof import('./src/components/AnnonceTravauxListe.vue')['default']
    CallerInfo: typeof import('./src/components/CallerInfo.vue')['default']
    CallerIsInGroup: typeof import('./src/components/CallerIsInGroup.vue')['default']
  }
}
